### ISSUE TITLE
How do I build for Android?

### ISSUE THREAD

**Issue by Gymcap** [benjamindean/observatory#6]
I was looking for an app for ITAD and found your lovely looking project. At first I thought it was IOS only, but then I noticed the Android folder in the repo. I was wondering if you could help/guide me to building an Android build? I would really love an app like this on my device.

**Comment by benjamindean** [comment]
Hey! The app is actually planned to release on Android (and I'm also developing using Android emulator), but Google being very difficult with identify verification, so the process stopped for now. 

As an option, I can set up a build with an .apk in GitHub releases. Would that work? I was planning to release a new version this week anyway.

**Comment by benjamindean** [comment]
I added a new release with an .apk in it: https://github.com/benjamindean/observatory/releases/tag/v1.3.0

@Gymcap Could you, please, test it out on your device? I don't have a physical Android phone at the moment.

**Comment by Gymcap** [comment]
I have installed the .apk release and it seems to be working fantastically! It requests notification permissions when enabling notifications as expected, app runs smoothly, I can seemingly interact with everything with no issues.

I happen to be someone who rarely, if ever, goes to the Google Play Store looking for apps. I more often will go to [F-Droid](https://f-droid.org/) to find open source, usually more privacy friendly options. I would highly recommend considering to add your app to F-Droid! I also use an Android app called [Obtanium](https://github.com/ImranR98/Obtainium) to pull apps directly from GitHub releases. Many people use these methods to get apps, and if you are interested in more android users having access to your app, then I believe releasing on F-Droid might help get it in front of more eyes.

The app is working beautifully, and I greatly appreciate that you built and published this release on my request, that was very kind :)

**Comment by benjamindean** [comment]
No problem! And thank you for the suggestion. I got so fixated on the idea of releasing the app on Play Store that I forgot that Android users can just install an apk. Mainly because I have some in-app purchases for supporting the app development and they're only possible if you release the app officially. 

I was looking into releasing the app on F-Droid in the future though. But for now I'll probably implement some update notifications from GitHub releases until the whole Play Store verification is sorted out. 

As for the privacy, that's mainly the reason I don't have any tracking inside the app and no account requirement for now. The only downside is that reinstalling the app will wipe your waitlist and all the other settings. 

In any case, thank you for the feedback and I hope that it will help you save some money in the future!
